# version: "3.8" // menghilangkan warning obsolete

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik_router
    command:
      - "--log.level=DEBUG" # TAMBAHKAN BARIS INI
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=lostfound_net" # FIX 1: Beritahu Traefik nama jaringannya
      - "--entrypoints.web.address=:80" # Pastikan huruf kecil semua
      # TAMBAHKAN BARIS INI UNTUK WINDOWS:
      - "--providers.docker.endpoint=tcp://host.docker.internal:2375"
    ports:
      - "80:80"
      - "8080:8080"
    # MATIKAN SEMENTARA VOLUMES SOCK INI:
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lostfound_net

  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: laravel_api
    volumes:
      - ./backend-api:/var/www/html
    ports:
      - "8000:8000" # JALAN PINTAS EMAS: Buka pintu langsung ke Windows!
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - lostfound_net

networks:
  lostfound_net:
    driver: bridge
    name: lostfound_net # FIX 3: Paksa Docker menggunakan nama murni tanpa embel-embel nama folder!
